name: Update Dictionary
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: | 
          npm ci
      - name: Update Dictionary Typescript File
        run: | 
          npm run update-dictionary
      - name: Bundle Files
        run: | 
          npm run build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Dictionary
          title: Update Dictionary Files
          body: Generate new files for using dictionary outside this package
          branch: update-dictionary