name: Tag on updated dictionary

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Bump tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'update-dictionary'

    steps:
    - uses: actions/checkout@v2

    - name: Create an incremental release
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: true
        message: Bump version
        prev_tag: 'v'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}